MCU = RP2040
BOOTLOADER = rp2040

# PIO serial/WS2812 drivers must be used on RP2040
SERIAL_DRIVER = vendor

#SPACE SAVING
AUDIO_ENABLE = no
MUSIC_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
